### ISSUE TITLE
Autocomplete for VSCode MATLAB terminal

### ISSUE THREAD

**Issue by bjmarfito** [mathworks/MATLAB-extension-for-vscode#159] opened 2024-07-08 02:39 UTC
**Is your feature request related to a problem? Please describe.**
I would like to suggest if MATLAB terminal can autocomplete codes added in MATLAB path by pressing TAB key.

**Describe the solution you'd like**
For exmaples, when I used MATLAB terminal in VSCode it autocompletes the code or gives suggestions which is the same as with MATLAB GUI Desktop Command Window.

**Describe alternatives you've considered**

**Additional context**

**Comment by dklilley** [comment] 2024-07-08 12:50
Thanks for the request!

I believe this is the same as #104 , so I am going to close this as a duplicate of that issue. If that issue does not capture your request accurately, please feel free to add a comment!

**Closed by dklilley** 2024-07-08 12:50 UTC
Labels: enhancement
