### ISSUE TITLE
MATLAB connection fails

### ISSUE THREAD

**Issue by wilkes-s** [mathworks/MATLAB-extension-for-vscode#38] opened 2023-06-22 12:53 UTC
### Issue Description

When trying to establish connection to matlab this fails with this message: 
matlabls - WARNING: Error while communicating with MATLAB - disconnecting

### LOGS:
[matlabls.log](https://github.com/mathworks/MATLAB-extension-for-vscode/files/11834090/matlabls.log)
[matlabLanguageServerLog.txt](https://github.com/mathworks/MATLAB-extension-for-vscode/files/11834092/matlabLanguageServerLog.txt)

**Comment by dklilley** [comment] 2023-06-27 20:26
Thank you for reporting this issue.

I haven't been able to reproduce this yet. Can you share some info about your environment:
1. Operating system
2. VS Code version

Thanks!

**Comment by wilkes-s** [comment] 2023-06-28 12:24
Hello,
1. Windows 10 10.0.19045 
2. Version: 1.79.2 (system setup)
3. Yes I am able to launch Matlab normally

**Comment by dklilley** [comment] 2023-06-30 20:17
@wilkes-s - I would like to try to get a bit more logging/debug info, but don't want to ask you to post it to GitHub as it may contain some info about your code and machine. Can you reach out to support@mathworks.com and reference this issue?

I will follow back up on this issue once we have identified the root cause.

**Comment by jankap** [comment] 2023-08-05 14:29
I have the same issue.

Matlab 2023a with new and old desktop experience tested. Status is always "Establishing Connection", then I get an error "Matlab has been closed. Some functionality might be unavailable". I see that Matlab starts in background in the task manager.
In fact, it starts each time I click on "Restart MATLAB", and it doesn't close anymore:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/12893844/e4c31f34-8c94-4c3a-b162-b2232813c33c)

The MATLAB LS log in VSCode is not very verbose:

> (16:27:12) matlabls: Launching MATLAB...
> (16:27:22) matlabls: Started MATLAB
> [Warn  - 4:27:22 PM] (16:27:22) matlabls - WARNING: Error while communicating with MATLAB - disconnecting

I'm using Matlab extension v1.1.1, and VSCode 1.81.0

**Comment by guntern** [comment] 2023-08-17 10:39
I have the same issue. It was working before and stopped recently.
My versions:
* Windows 10
* Matlab 2022b (even though also 2017b is installed, but apparently 2022b gets started)
* VSCode 1.82.0-insider
* Matlab extension 1.1.2

**Comment by dklilley** [comment] 2023-09-05 14:56
Sorry for the late response to this thread.

This issue is likely an issue with the firewall or proxy. The following steps could be used to confirm this:

1. Close all open instances of MATLAB and VS Code
2. Open VS Code and attempt to connect to MATLAB
3. In the Windows Task Manager, find the line item for MATLAB. This will likely be collapsed under "Visual Studio Code" in the "Apps" list, but may also appear as its own background process.
4. Right-click on "MATLAB R2022b" and select "Go to details" - make note of the PID for the highlighted row
5. Open a Command Prompt (I believe they may need to open as administrator for the next step)
6. Run the following command, replacing FILE with a file path they choose: netstat -anob > FILE
        This will save the output of the netstat command (which includes IP addresses w/ ports, and the respective applications) to the file path provided
7. In this file, search for a "LISTENING" connection for the PID noted in step (4) - note the IP address listed in the second column (should be listed as 127.0.0.1:PORT)
8. From the command prompt, execute the following command (replacing for the IP address noted above): curl -v -k https://127.0.0.1:PORT

**Comment by biiigwang** [comment] 2023-09-08 10:36
I have the same issue. It was working before and stopped recently.
My versions:
```log
Windows 11 22H2
Matlab 2022b
# vscode info
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

When I opened the VS code and attempted to connect to MATLAB, I received the following log. May I know how to resolve it
```bash
(18:28:33) matlabls: Launching MATLAB...
(18:28:43) matlabls: Started MATLAB
(node:15496) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `Code --trace-warnings ...` to show where the warning was created)
[Warn  - 6:28:43 PM] (18:28:43) matlabls - WARNING: Error while communicating with MATLAB - disconnecting
```

**Comment by ehehela** [comment] 2023-09-09 00:48
I have the similar problem. It popped up the warning message since the vscode updated to version 1.81.

> MATLAB has been closed. Some functionality might be unavailable.

**Comment by FannoFlow** [comment] 2023-09-10 23:56
I have the same issues on 
Windows 11
VSCode Insiders 1.83
MATLAB v1.1.2 
MATLAB R2022b

I believe this is related to https://github.com/mathworks/MATLAB-language-server/issues/10 

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/20805014/ff95fde0-0c92-43a1-9110-ada929c827f5)

**Comment by FannoFlow** [comment] 2023-09-11 00:11
Users on discord reporting the same problem

https://discord.com/channels/315631984489791488/450928036800364546/1150564402123243572

**Comment by guntern** [comment] 2023-09-11 06:48
> Sorry for the late response to this thread.
> 
> This issue is likely an issue with the firewall or proxy. The following steps could be used to confirm this:
> 
>     1. Close all open instances of MATLAB and VS Code
> 
>     2. Open VS Code and attempt to connect to MATLAB
> 
>     3. In the Windows Task Manager, find the line item for MATLAB. This will likely be collapsed under "Visual Studio Code" in the "Apps" list, but may also appear as its own background process.
> 
>     4. Right-click on "MATLAB R2022b" and select "Go to details" - make note of the PID for the highlighted row
> 
>     5. Open a Command Prompt (I believe they may need to open as administrator for the next step)
> 
>     6. Run the following command, replacing FILE with a file path they choose: netstat -anob > FILE
>        This will save the output of the netstat command (which includes IP addresses w/ ports, and the respective applications) to the file path provided
> 
>     7. In this file, search for a "LISTENING" connection for the PID noted in step (4) - note the IP address listed in the second column (should be listed as 127.0.0.1:PORT)
> 
>     8. From the command prompt, execute the following command (replacing for the IP address noted above): curl -v -k https://127.0.0.1:PORT

Thank you very much for the steps. But what is the expected outcome at the end?

I followed the steps and received a response from `curl` which states "The connector service is running". So apparently I can reach it with curl.

Afterwards I once again tried to connect from VS Code, but it still did not work.

**Comment by guntern** [comment] 2023-09-11 06:49
> Users on discord reporting the same problem
> 
> https://discord.com/channels/315631984489791488/450928036800364546/1150564402123243572

What discord server is this?

**Comment by SamReinsel** [comment] 2023-09-12 13:26
I'm also having the same issue on one of my machines after updating VScode to 1.82, while my other machine which is still on 1.81 is not having issues.

**Comment by rq-Chen** [comment] 2023-09-12 20:56
Same issue for me after updating VS code

> ### Connection failed after updating vscode to 1.82
> I have the similar problem. It popped up the warning message since the vscode updated to version 1.82.
> 
> > MATLAB has been closed. Some functionality might be unavailable.
> 
> TCP 127.0.0.1:55770 127.0.0.1:7890 ESTABLISHED 13296 [MATLAB.exe]
> 
> * Trying 127.0.0.1:55770...
> * connect to 127.0.0.1 port 55770 failed: Connection refused
> * Failed to connect to 127.0.0.1 port 55770 after 2044 ms: Couldn't connect to server
> * Closing connection 0
>   curl: (7) Failed to connect to 127.0.0.1 port 55770 after 2044 ms: Couldn't connect to server

**Comment by dklilley** [comment] 2023-09-13 16:36
This issue should be resolved now (c32ba24). This has been released as v1.1.3 of the extension, and is available for download/update now.

Please let me know if you still experience this issue after updating. For now, I am closing this issue.

**Closed by dklilley** 2023-09-13 16:36 UTC
Labels: bug

**Comment by plwalsh** [comment] 2023-11-06 14:03
I'm on extension version v1.1.4 and still seeing this issue.

```
Version: 1.85.0-insider (user setup)
Commit: 9aacac648821b5c9c1a7192ac9d44c50af6fe241
Date: 2023-11-06T05:34:22.485Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

I've tried closing all running instances of MATLAB, and clicking "End task" inside Task Manager for anything that said "MATLAB", and then trying again, but nothing has worked. I always end up with the same `matlabLanguageServerLog.txt` shown in the OP.

And I don't have admin rights on this work PC, so I can't run the `netstat` command.

**Comment by jankap** [comment] 2023-12-04 11:24
> I'm on extension version v1.1.4 and still seeing this issue.
> 
> ```
> Version: 1.85.0-insider (user setup)
> Commit: 9aacac648821b5c9c1a7192ac9d44c50af6fe241
> Date: 2023-11-06T05:34:22.485Z
> Electron: 25.9.2
> ElectronBuildId: 24603566
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Windows_NT x64 10.0.19045
> ```
> 
> I've tried closing all running instances of MATLAB, and clicking "End task" inside Task Manager for anything that said "MATLAB", and then trying again, but nothing has worked. I always end up with the same `matlabLanguageServerLog.txt` shown in the OP.

Same here, there are lots of instances spawned but I can't speak to them using curl - connection refused.

Important note: I'm behind a corporate proxy, but I've set $no_proxy=localhost,127.0.0.1. Anything else to be set?
Also note, ZScaler (the mandatory proxy running here) spawns its own server at localhost:9000, does this inference with mathworks solution?

> 
> ETA: It also keeps opening more and more MATLAB processes in the background every time it tries to reconnect. And doesn't clean them up upon disconnecting. Seems very messy.

Same here, instances are not closed.

**Comment by plwalsh** [comment] 2023-12-20 14:20
> Important note: I'm behind a corporate proxy, but I've set $no_proxy=localhost,127.0.0.1. Anything else to be set? Also note, ZScaler (the mandatory proxy running here) spawns its own server at localhost:9000, does this inference with mathworks solution?

@jankap Just an FYI, but after working with MATLAB support, it was determined that the `NO_PROXY` variable is not respected by the extension, and thus the extension does not work in proxy-supported environments. They attributed it to a potential issue with Node.js, though I'm not entirely clear as to why. According to https://github.com/microsoft/vscode/issues/68260#issuecomment-478480552, `NO_PROXY` support was added to extensions back in 2019.

**Comment by jankap** [comment] 2023-12-20 17:26
Thanks @plwalsh for letting me know. However I can't imagine Mathworks does not support corporate environments, which almost all use some kind of proxy. I'll open a support ticket, too, and hope that there will be some progress here as well.

**Comment by jankap** [comment] 2024-03-18 14:57
My problem is still persistent, even with the latest extension release v1.2.0 and Matlab R2024a pre.
I'm on Windows 10 in a corporate environment with ZScaler. `HTTP_PROXY` and `NO_PROXY` variables are set properly.

@dklilley could you please help me checking again?

I've closed all matlab instances via task manager and then restarted the connection in VSCode. 
Two services seem to run:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/12893844/21cff68a-5878-4d40-8f9b-4a81aab858e5)

after a few seconds, the disconnecting info shows up:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/12893844/da1b26d9-3df5-47ad-a6c7-6cdfb52f1769)

and four matlab ports remain open:

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/12893844/80963174-8686-4345-b3e0-e503383c9ab1)

I tried to connect to all of them via `curl -k -v https://127.0.0.1:49923` and adjusting the port:
```
C:\Users\username> curl -k -v https://127.0.0.1:49923
* Uses proxy env variable no_proxy == 'localhost,127.0.0.1'
*   Trying 127.0.0.1:49923...
* connect to 127.0.0.1 port 49923 failed: Connection refused
* Failed to connect to 127.0.0.1 port 49923 after 2015 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 127.0.0.1 port 49923 after 2015 ms: Couldn't connect to server
```
Same for the others.

Since there is no connection `LISTENING` anymore, can I start the service manually via commandline to take the VSCode extension out of the game?

Of course, running matlab standalone works properly.

Thanks for any support!

**Comment by albheim** [comment] 2024-03-28 10:52
Seeing the same thing. Matlab process starts, can find the listening port and curl gives "service is running ... connection left intact" stuff, but vscode just says "matlabls - WARNING: Error while communicating with MATLAB - disconnecting". 
Have a corporate proxy, but no_proxy variables are set for localhost. 
Extension version 1.2.0

**Comment by dklilley** [comment] 2024-03-28 14:04
Sorry for the delayed response - we are still looking into this and are working to find a solution. Unfortunately, something in the pipeline is disregarding the NO_PROXY environment variables. We are looking into workarounds to ensure these environment variables are respected.
