### ISSUE TITLE
Code navigation for files under open project

### ISSUE THREAD

**Issue by shenhai-ran** [mathworks/MATLAB-extension-for-vscode#109] opened 2024-03-11 22:26 UTC
It looks like `Go To Definition`  and similar features only works for files which are added to the MATLAB path. When I open a project at VSCode, not all my projects files are added to path at startup, and it is not possible for code navigation actions.
 
It would be nice to automatically add files under my open project into path for code navigation. A project root maybe detected by .git or MATLAB project folder.

**Comment by dklilley** [comment] 2024-03-12 19:10
Thanks for raising this request! I believe this is the same as #98, so I am closing this as a duplicate of that issue.

**Closed by dklilley** 2024-03-12 19:10 UTC
Labels: enhancement
