### ISSUE TITLE
Incorrect indentation after multi-line statements

### ISSUE THREAD

**Issue by goldrik** [mathworks/MATLAB-extension-for-vscode#90] opened 2024-02-07 18:23 UTC
When typing a multi-line statement, VS Code incorrectly indents the lines following it. 

https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/2f3ecffe-0beb-442b-b623-4320a3346f66

If you type the same lines in the official MATLAB IDE, this indentation does not occur because MATLAB correctly identifies this indent as part of a mutli-line statement. 

https://github.com/mathworks/MATLAB-extension-for-vscode/assets/8674612/2c42fcc9-ad98-421f-86b7-e9800c76807a

This is related to Issue #85, where the extension does not seem to handle multi-line statements correctly in general.

**Comment by dklilley** [comment] 2024-02-07 18:26
Closing this as a duplicate of #85. The fix for that issue should address this as well.

**Closed by dklilley** 2024-02-07 18:26 UTC
Labels: bug
