### ISSUE TITLE
Go to definition not working with packages

### ISSUE THREAD

**Issue by vilhei** [mathworks/MATLAB-extension-for-vscode#25] opened 2023-05-17 05:58 UTC
Go to definition is not working for me when using packages.
I have attached a small example where if inside function test() I try to go to util.sum definition it does nothing. 
With Matlab editor this works fine. 

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/81528449/479b1b9b-b98e-4d95-ba02-e930cba66f10)

EDIT:
Upon restarting vscode it works fine some times but other times it does not work. 
I have not found a reason for this or a way to reproduce it every time.

**Comment by SamReinsel** [comment] 2023-05-17 12:47
This might be a repeat of #5 

Is this package in your MATLAB pathdef? as mentioned in #5 I don't have any problem with packages that are permanently on my path via `savepath`, but packages not on my default path don't seem to get picked up.

**Comment by dklilley** [comment] 2023-05-30 18:48
I agree with Sam, I think this is a duplicate of #5.

I am closing this as a duplicate. Please feel free to comment if you believe this is a separate issue.

**Closed by dklilley** 2023-05-30 18:48 UTC
