### ISSUE TITLE
MATLAB was unable to start

### ISSUE THREAD

**Issue by denissagaydak** [mathworks/MATLAB-extension-for-vscode#58] opened 2023-09-19 10:34 UTC
Windows 10 21H2
VSCode 1.82.2
MATLAB Extension 1.1.3
MATLAB 2022b

Tried restarting/closing VSCode, MATLAB and restarting PC. 
Tried installing MATLAB in folder without whitespace.
Tried MATLAB 2021b and previous versions of MATLAB Extension;

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/16610721/6c2be36d-6acf-43ca-9741-22ab5137cb6b)

**Comment by dklilley** [comment] 2023-09-20 15:13
Can you provide the following info:
1. Launch MATLAB separately and run `matlabroot`. Is the value you have provided in the "Install Path" setting the same as what MATLAB is outputting?
2. Can you confirm that there is no trailing or preceding whitespace in the "Install Path" text field?
3. In VS Code, open the Output tab (Ctrl+Shift+U) and select "MATLAB Language Server" from the dropdown. Please share any errors displayed in this log.

**Comment by denissagaydak** [comment] 2023-09-21 07:04
Hello @dklilley,

1. matlabroot returns the same path, as specified in "Install Path" setting
3. Yes, there are no extra whitespaces in "Install Path" setting
4. Here is "MATLAB Language Server" output : 
(08:58:36) matlabls: Launching MATLAB...
[Error - 8:58:36 AM] (08:58:36) matlabls - ERROR: Error launching MATLAB: spawn C:\Program Files\MATLAB\R2022b\bin\matlab ENOENT
[Error - 8:58:36 AM] (08:58:36) matlabls - ERROR: Error launching MATLAB: Error
[Error - 8:58:36 AM] (08:58:36) matlabls - ERROR: Error launching MATLAB: Error: spawn C:\Program Files\MATLAB\R2022b\bin\matlab ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(08:58:36) matlabls: MATLAB process terminated

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/16610721/59a6980f-bc7d-4f82-aec5-bd37551ee5a0)
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/16610721/60f14461-fb83-4367-afce-da62f69996f6)

**Comment by M-Moschetti** [comment] 2024-01-11 02:42
Same issue.

Windows 10.0.19045 22H2
VS Code 1.85.1
VS Code MATLAB extension v1.1.5
MATLAB 2023b

Steps taken:
- Restarted VS Code, MATLAB and PC.
- Reinstalled VS Code and MATLAB extension.
- Quadruple checked the MATLAB path in the extension and ensured it was the same as the 'matlabroot' output.

MATLAB Language Server output:

> (13:17:04) matlabls: Log Directory: C:\Users\z5165928\AppData\Local\Temp\matlabls_1052
> (13:17:04) matlabls: Launching MATLAB...
> [Error - 1:17:04 PM] (13:17:04) matlabls - ERROR: Error finding mlint executable in C:\Program Files\MATLAB\R2023b\bin
> [Error - 1:17:04 PM] (13:17:04) matlabls - ERROR: Error launching MATLAB: spawn C:\Program Files\MATLAB\R2023b\bin\matlab ENOENT
> [Error - 1:17:04 PM] (13:17:04) matlabls - ERROR: Error launching MATLAB: Error
> [Error - 1:17:04 PM] (13:17:04) matlabls - ERROR: Error launching MATLAB: Error: spawn C:\Program Files\MATLAB\R2023b\bin\matlab ENOENT
>     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> (13:17:04) matlabls: MATLAB process terminated

**Comment by dklilley** [comment] 2024-01-11 15:14
Thanks for reporting this. I have not been able to reproduce this on my machine, but here are a few things to try/check:
1. Is there any leading/trailing whitespace in the `installPath` setting's text field in VS Code? This probably isn't the issue, but has been known to cause problems.
2. From a system command window, does running the following (including the double quotes) launch MATLAB correctly?
`"C:\Program Files\MATLAB\R2023b\bin\matlab.exe"` 
3. Does running `matlab` from a system command window launch MATLAB? On Windows, the extension will attempt to launch MATLAB with the `matlab` command if no path is provided in the setting. If this command works on your machine, try clearing the `installPath` setting.

**Comment by M-Moschetti** [comment] 2024-01-11 16:06
I can confirm that there are no leading/trailing white spaces.

Both options 2. and 3. successfully launch MATLAB. Clearing the Install
Path settings changed nothing.

Thanks for your help.

**Comment by M-Moschetti** [comment] 2024-01-12 23:10
No, I am not.

**Comment by MiuKaShi** [comment] 2024-01-13 14:53
Same problem in MATLAB-language-server, https://github.com/mathworks/MATLAB-language-server/issues/33. 
So  May cause by MATLAB-language-server ?

**Comment by dklilley** [comment] 2024-04-04 17:27
Hi all,
If you have a chance, can you try this again with the new release of the extension (v1.2.1) and let us know if you are still encountering this issue?

**Comment by M-Moschetti** [comment] 2024-04-05 00:37
I no longer have access to the offending machine, so I cannot test this. My
apologies.

**Comment by dklilley** [comment] 2024-04-10 15:03
@M-Moschetti no worries, thank you for the response!

**Comment by dklilley** [comment] 2024-06-26 17:15
I believe this is likely resolved. Closing this issue for now.

**Closed by dklilley** 2024-06-26 17:15 UTC
Labels: bug

**Comment by sbom641** [comment] 2024-07-23 10:16
I am experiencing the same problem 
VS code - 1.91.1
MATLAB - 2023b
Matlab Extension for VS Code - v1.2.4
Windows - 11Pro 23H2

![image](https://github.com/user-attachments/assets/5fed39ed-3046-48a1-be50-5eaa902c010b)

![image](https://github.com/user-attachments/assets/3319122d-91ad-4c18-be20-204165e7207e)

This is the only error message I keep getting: 
![image](https://github.com/user-attachments/assets/d69fc1b0-f072-44ce-a2e4-18ea17362f12)
(I do not get see any errros outputed to the OUTPUT tab in VS Code)

Any help is appreciated.

**Comment by dklilley** [comment] 2024-07-23 12:49
Hi @sbom641 , since this issue is closed, can you open a new issue for this? Thanks!
