### ISSUE TITLE
Code-folding for functions sometimes stops within the function for no discernable reason

### ISSUE THREAD

**Issue by anakinsleftleg** [mathworks/MATLAB-extension-for-vscode#16] opened 2023-05-05 19:08 UTC
Sometimes the function code folding will fold the entire function, but other times, the fold will stop 15 lines in, or 130 lines in. The stop lines don't have anything obviously unique about them. I can't really share the code but I'd like to help debug it.

**Comment by dklilley** [comment] 2023-05-09 16:21
Thanks for reporting this!

Does this reliably happen with certain functions, or does the behavior vary when folding/unfolding repeatedly?

> I can't really share the code

I'm not sure whether you mean that this is not reliably reproducible, or you cannot share the code for security/confidentiality reasons. If this is the second, could you try to create a more simple and generic function which reproduces the issue, or describe the structure of the function (i.e. does it contain lots of if-statements, loops, nested functions, etc.)?

**Comment by anakinsleftleg** [comment] 2023-05-10 16:59
It reliable happens with certain functions. If I fold and unfolder repeatedly, it behaves the same. 

They are generally part of large files with many functions and if-statements, loops etc. I haven't seen the issue on shorter functions. I'll see if I can reproduce with code that is non-descript.

**Comment by anakinsleftleg** [comment] 2023-05-10 17:06
This comes from a much larger function but i found that within itself, it shows this issue. I copied it to its own file and still has the behavior.

```matlab
  % Process tilt plot
  if (numel(dataStruct) > 1 || ~flagNoSingleTiltPlot) && numel(uniquerows(structfield2array(dataStruct(1).DataProcessed, ["X_Fieldpoint_ScanPlane_mm", "Y_Fieldpoint_ScanPlane_mm"]))) > 2
    pointLabels = vertcat(dataStruct.DataProcessed);
    figStruct(numel(figStruct) + 1, 1).Plot = displayPlaneFit(createDataStructPointcloud(dataStruct), dataStruct(1).ComboTiltCoefficients, dataStruct(1).Params.fieldpointSpaceToScanSpaceScaling, structfield2array(pointLabels, "CurveLabel"), vertcat(dataStruct.DatasetName), dataStruct(1).ComboBestFocus, dataStruct(1).Params.isTiltSpaceInScanSpace).tiltFigure;
    figStruct(end).Plot.Name = replace(figStruct(1).Plot.Name, " Field Overlap", " Tilt Plot");
    figStruct(end).Filename = replace(figStruct(1).Filename, " Field Overlap", " Tilt Plot");
    figStruct(end).Folderpath = figStruct(1).Folderpath;
    printVersionsOnFigure(figStruct(end).Plot, versionString);
  end
```

The fold chevron appears at the if statement, but when I click it, it folds until line 6 
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/77084568/e2489c55-50ed-4b24-89d8-5a50cf1280c3)

![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/77084568/3102ab9d-e409-4419-9d81-0cac30bd4b6c)

Other occurrences similar to this happen with for and function folds (and this directly affects the behavior of the sticky lines which stay at the top of the editor as you scroll through code to give you context of what nest you are in, the stickyness ends where the folds prematurely end).

**Comment by dklilley** [comment] 2023-05-11 13:57
Ah, code folding seems to be getting confused when there is an `end` being used to indicate the last index of an array.

I can also reproduce this with a very simplified example:
```matlab
if true
    x = [1 2 3];
    x(end + 1) = 4;
    x(end + 1) = 5;
end
```

**Comment by anakinsleftleg** [comment] 2023-05-12 00:45
Glad it's reproducible! How on earth did you pinpoint it to that? Can it be addressed?

**Comment by dklilley** [comment] 2023-05-12 14:47
I had a hunch that this might be the cause, since the [current implementation](https://github.com/mathworks/MATLAB-extension-for-vscode/blob/63faa85de6fc9c048539898edd7a9e5846cc6816/language-configuration.json) specifies code folding using regular expressions. This might be able to be addressed by modifying the regular expressions, or by leveraging [the LSP ability to specify folding ranges](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange).

**Comment by 614c0m1n5** [comment] 2023-05-24 06:16
> Ah, code folding seems to be getting confused when there is an `end` being used to indicate the last index of an array.
> 
> I can also reproduce this with a very simplified example:
> 
> ```matlab
> if true
>     x = [1 2 3];
>     x(end + 1) = 4;
>     x(end + 1) = 5;
> end
> ```

Code folding fails to recognize end keywords in comments too. So if you have a comment containing end it will be counted and code folding will not work as expected.

**Closed** 2023-05-31 20:32 UTC
Labels: bug

**Comment by dklilley** [comment] 2023-05-31 20:38
This should be resolved now, and will be released as an update to the extension soon.
